# Generated by Django 3.0.3 on 2020-02-16 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ER_test_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberPacket',
            fields=[
                ('packet_id', models.AutoField(primary_key=True, serialize=False)),
                ('packet_name', models.CharField(max_length=100)),
                ('packet_content', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataAboutSending',
            fields=[
                ('sending_id', models.AutoField(primary_key=True, serialize=False)),
                ('visits', models.IntegerField(default=0)),
                ('number_set_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ER_test_app.NumberPacket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
