# Generated by Django 3.0.3 on 2020-02-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ER_test_app', '0002_dataaboutsending_numberpacket'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to='profile_images'),
        ),
    ]
