# Generated by Django 3.0.3 on 2020-02-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ER_test_app', '0003_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataaboutsending',
            name='visits',
        ),
        migrations.AddField(
            model_name='dataaboutsending',
            name='message',
            field=models.FileField(default='somefile.mp3', upload_to='messages/'),
        ),
        migrations.AlterField(
            model_name='numberpacket',
            name='packet_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
